// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {core} from '../models';

export function Account():Promise<main.Account>;

export function CancelTrain(arg1:string):Promise<void>;

export function Change(arg1:string):Promise<core.ChangeView>;

export function Changes():Promise<Array<main.ChangeSummary>>;

export function Check(arg1:string,arg2:string):Promise<Array<main.CheckEvent>>;

export function Clean(arg1:Array<string>):Promise<Array<main.CleanResult>>;

export function CleanPlan():Promise<Array<main.CleanItem>>;

export function Editors():Promise<Array<main.EditorApp>>;

export function Focus(arg1:string):Promise<void>;

export function Inbox(arg1:boolean):Promise<main.Inbox>;

export function Link(arg1:string,arg2:string,arg3:string):Promise<void>;

export function OpenEditor(arg1:string):Promise<void>;

export function OpenFolder(arg1:string):Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function Pin(arg1:string):Promise<Array<main.PinItem>>;

export function PlanPRs(arg1:string,arg2:main.PRRequest):Promise<main.PRPreview>;

export function PublishPRs(arg1:string,arg2:main.PRRequest):Promise<main.PRPreview>;

export function Refresh(arg1:string):Promise<void>;

export function Repos():Promise<Array<main.RepoInfo>>;

export function SaveSettings(arg1:main.Settings):Promise<main.Settings>;

export function Settings():Promise<main.Settings>;

export function SettingsPath():Promise<string>;

export function Start(arg1:main.StartRequest):Promise<Array<main.StartItem>>;

export function StartTrain(arg1:string,arg2:string):Promise<void>;

export function Switch(arg1:string,arg2:boolean):Promise<Array<main.LegResult>>;

export function Sync(arg1:string):Promise<Array<main.LegResult>>;

export function SystemDark():Promise<boolean>;

export function TandemHome():Promise<string>;

export function TrainPlan(arg1:string):Promise<main.TrainPlan>;

export function Version():Promise<string>;
