// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Account() {
  return window['go']['main']['App']['Account']();
}

export function AddRepos(arg1, arg2) {
  return window['go']['main']['App']['AddRepos'](arg1, arg2);
}

export function CancelTrain(arg1) {
  return window['go']['main']['App']['CancelTrain'](arg1);
}

export function Change(arg1) {
  return window['go']['main']['App']['Change'](arg1);
}

export function Changes() {
  return window['go']['main']['App']['Changes']();
}

export function Check(arg1, arg2) {
  return window['go']['main']['App']['Check'](arg1, arg2);
}

export function Clean(arg1) {
  return window['go']['main']['App']['Clean'](arg1);
}

export function CleanPlan() {
  return window['go']['main']['App']['CleanPlan']();
}

export function Editors() {
  return window['go']['main']['App']['Editors']();
}

export function Focus(arg1) {
  return window['go']['main']['App']['Focus'](arg1);
}

export function Inbox(arg1) {
  return window['go']['main']['App']['Inbox'](arg1);
}

export function Link(arg1, arg2, arg3) {
  return window['go']['main']['App']['Link'](arg1, arg2, arg3);
}

export function OpenEditor(arg1) {
  return window['go']['main']['App']['OpenEditor'](arg1);
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function Pin(arg1) {
  return window['go']['main']['App']['Pin'](arg1);
}

export function PlanPRs(arg1, arg2) {
  return window['go']['main']['App']['PlanPRs'](arg1, arg2);
}

export function PublishPRs(arg1, arg2) {
  return window['go']['main']['App']['PublishPRs'](arg1, arg2);
}

export function Refresh(arg1) {
  return window['go']['main']['App']['Refresh'](arg1);
}

export function RemoveLeg(arg1, arg2) {
  return window['go']['main']['App']['RemoveLeg'](arg1, arg2);
}

export function Repos() {
  return window['go']['main']['App']['Repos']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function Settings() {
  return window['go']['main']['App']['Settings']();
}

export function SettingsPath() {
  return window['go']['main']['App']['SettingsPath']();
}

export function Start(arg1) {
  return window['go']['main']['App']['Start'](arg1);
}

export function StartTrain(arg1, arg2) {
  return window['go']['main']['App']['StartTrain'](arg1, arg2);
}

export function Switch(arg1, arg2) {
  return window['go']['main']['App']['Switch'](arg1, arg2);
}

export function Sync(arg1) {
  return window['go']['main']['App']['Sync'](arg1);
}

export function SystemDark() {
  return window['go']['main']['App']['SystemDark']();
}

export function TandemHome() {
  return window['go']['main']['App']['TandemHome']();
}

export function TrainPlan(arg1) {
  return window['go']['main']['App']['TrainPlan'](arg1);
}

export function Unlink(arg1, arg2, arg3) {
  return window['go']['main']['App']['Unlink'](arg1, arg2, arg3);
}

export function Version() {
  return window['go']['main']['App']['Version']();
}
