// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';
import {main} from '../models';

export function Change(arg1:string):Promise<core.ChangeView>;

export function Changes():Promise<Array<main.ChangeSummary>>;

export function Check(arg1:string,arg2:string):Promise<Array<main.CheckEvent>>;

export function Focus(arg1:string):Promise<void>;

export function Inbox(arg1:boolean):Promise<main.Inbox>;

export function Link(arg1:string,arg2:string,arg3:string):Promise<void>;

export function OpenEditor(arg1:string):Promise<void>;

export function OpenFolder(arg1:string):Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function PlanPRs(arg1:string,arg2:main.PRRequest):Promise<main.PRPreview>;

export function PublishPRs(arg1:string,arg2:main.PRRequest):Promise<main.PRPreview>;

export function Refresh(arg1:string):Promise<void>;

export function Repos():Promise<Array<main.RepoInfo>>;

export function Start(arg1:main.StartRequest):Promise<Array<main.StartItem>>;

export function Sync(arg1:string):Promise<Array<main.LegResult>>;
