// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {core} from '../models';
import {triage} from '../models';
import {testrun} from '../models';

export function Account():Promise<main.Account>;

export function AddRepos(arg1:string,arg2:Array<string>):Promise<Array<main.StartItem>>;

export function BranchRepos(arg1:string):Promise<Array<main.BranchInfo>>;

export function CancelTrain(arg1:string):Promise<void>;

export function Change(arg1:string):Promise<core.ChangeView>;

export function Changes():Promise<Array<main.ChangeSummary>>;

export function Check(arg1:string,arg2:string):Promise<Array<main.CheckEvent>>;

export function Clean(arg1:Array<string>):Promise<Array<main.CleanResult>>;

export function CleanPlan():Promise<Array<main.CleanItem>>;

export function CommitPins(arg1:string):Promise<Array<main.LegResult>>;

export function Discard(arg1:string):Promise<main.CleanResult>;

export function DiscardPlan(arg1:string):Promise<main.CleanItem>;

export function Editors():Promise<Array<main.EditorApp>>;

export function Focus(arg1:string):Promise<void>;

export function Inbox(arg1:boolean):Promise<main.Inbox>;

export function JiraAccount():Promise<main.JiraAccount>;

export function JiraLookup(arg1:string):Promise<main.JiraTicket>;

export function Link(arg1:string,arg2:string,arg3:string):Promise<void>;

export function OpenEditor(arg1:string):Promise<void>;

export function OpenFolder(arg1:string):Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function Pin(arg1:string):Promise<Array<main.PinItem>>;

export function PlanPRs(arg1:string,arg2:main.PRRequest):Promise<main.PRPreview>;

export function PublishPRs(arg1:string,arg2:main.PRRequest):Promise<main.PRPreview>;

export function Refresh(arg1:string):Promise<void>;

export function RemoveLeg(arg1:string,arg2:string):Promise<string>;

export function Rename(arg1:string,arg2:string):Promise<void>;

export function Reorder(arg1:Array<string>):Promise<void>;

export function Repos():Promise<Array<main.RepoInfo>>;

export function SaveJira(arg1:string,arg2:string):Promise<main.JiraAccount>;

export function SaveSettings(arg1:main.Settings):Promise<main.Settings>;

export function SetTicket(arg1:string,arg2:string):Promise<void>;

export function Settings():Promise<main.Settings>;

export function SettingsPath():Promise<string>;

export function Start(arg1:main.StartRequest):Promise<Array<main.StartItem>>;

export function StartTrain(arg1:string,arg2:string):Promise<void>;

export function Switch(arg1:string,arg2:boolean):Promise<Array<main.LegResult>>;

export function Sync(arg1:string):Promise<Array<main.LegResult>>;

export function SystemDark():Promise<boolean>;

export function TandemHome():Promise<string>;

export function TestTriage(arg1:triage.Config):Promise<string>;

export function TesterFinish(arg1:string,arg2:string):Promise<main.TestFinish>;

export function TesterPlan(arg1:string):Promise<main.TesterPlan>;

export function TesterPull():Promise<Array<testrun.Step>>;

export function TesterQueue(arg1:boolean):Promise<main.TesterQueue>;

export function TesterStart(arg1:main.TestStartRequest):Promise<Array<testrun.Step>>;

export function TesterState():Promise<testrun.State>;

export function TesterStatus():Promise<Array<testrun.RepoStatus>>;

export function TrainPlan(arg1:string):Promise<main.TrainPlan>;

export function Unlink(arg1:string,arg2:string,arg3:string):Promise<void>;

export function Version():Promise<string>;
